services:
  job-server:
    container_name: job-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - job_service_flyway
      - job_service_db
      - redis_stack_server
    networks:
      - carroll-network
  job_service_flyway:
    image: redgate/flyway
    command: migrate -connectRetries=60
    volumes:
      - ./src/main/resources/db/flyway/conf:/flyway/conf
      - ./src/main/resources/db/flyway/sql:/flyway/sql
    networks:
      - carroll-network
    depends_on:
      - job_service_db
  job_service_db:
    image: postgres:latest
    environment:
      - 'POSTGRES_DB=job_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=job_user'
    networks:
      - carroll-network
    ports:
      - 5432:5432
  redis_stack_server:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    networks:
      - carroll-network
networks:
  carroll-network:
    driver: bridge
